# Generated by Django 5.1.6 on 2025-03-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='tweet',
            new_name='tweet_msg',
        ),
    ]
