# Generated by Django 5.1.6 on 2025-03-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_rename_tweet_tweets_tweet_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='tweet_photos/'),
        ),
    ]
